library(magick)
library(tidyverse)

# Overview with plots generated by the protocols
file.rename("overview_of_protocols.png", "overview_of_protocols.bak")


# read the the png files into a list
pngfiles <-
  list.files(
    recursive = TRUE,
    pattern = "\\.png$",
    full.names = T
  )

n_columns <- floor(sqrt(length(pngfiles))) 

# read images and then create a montage
# tile =2 , means arrange the images in 2 columns
# geometry controls the pixel sixe, spacing between each image in the collage output. 

overview <- image_read(pngfiles) %>%
  image_montage(tile = n_columns, geometry = "x400+10+10")

overview

image_write(overview, path = "overview_of_protocols.png", format = "png")
